---
title: "Geography 176A"
author: "[Amy Kou](https://amykou43.github.io/amykou43/)"
subtitle: 'Lab 03: Distances and the Border Zone'
output:
  html_document:
    theme: journal
---


```{r, echo = FALSE, message= FALSE}
# SPDS
library(tidyverse)
library(sf)
library(units)

# Data
library(USAboundaries)
library(rnaturalearth)

# Visualization
library(gghighlight)
library(ggrepel)
library(knitr)
```



```{r, echo = FALSE, message= FALSE}

# remotes::install_github("ropensci/USAboundaries")
# remotes::install_github("ropensci/USAboundariesData")
# USAboundaries::us_states(resolution = "low")

eqdc = '+proj=eqdc +lat_0=40 +lon_0=-96 +lat_1=20 +lat_2=60 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs'

#1.1
conus = USAboundaries::us_states() %>%
  filter(!state_name %in% c("Puerto Rico",
                            "Alaska",
                            "Hawaii")) %>%
  st_transform(eqdc)


#1.2
state_boundaries = USAboundaries::us_states(resolution = "low") %>%
  filter(!state_name %in% c("Puerto Rico",
                            "Alaska",
                            "Hawaii")) %>%
  st_transform(eqdc)


#1.3

remotes::install_github("ropenscilabs/rnaturalearthdata")
countries = rnaturalearth::countries110 %>%
  st_as_sf(countries110, coors = c("lng", "lat"), 
         crs = 4269) %>%
  filter(admin %in% c("Canada","Mexico", "United States of America")) %>%
  st_transform(eqdc)


#1.4

cities <- read_csv("~/github/geog-176A-labs/data/uscities.csv") %>%
  st_as_sf(coords = c("lng", "lat"), crs = 4326) %>%
  filter(!state_name %in% c("Alaska", "Hawaii", "Puerto Rico")) %>%
  st_transform(eqdc)

```

```{r, echo = FALSE, message= FALSE}

#2.1

usa = st_union(state_boundaries) %>%
  st_cast("MULTILINESTRING")

cities = cities %>%
  mutate(dist_border = st_distance(cities, usa),
         dist_border = set_units(dist_border, "km"),
         dist_border = drop_units(dist_border))

Top5 = cities %>%
  select(city, state_name, dist_border) %>% 
  slice_max(dist_border, n = 5) %>% 
  st_drop_geometry()

```

```{r, echo = FALSE, message= FALSE}

#Table of top 5 farthest cities from US border 
knitr::kable(Top5, caption = 'farthest cities from US border',
             col.names = c("city name", "state", "distance"),
             format.args = list(big.mark = ","))

```

```{r, echo = FALSE, message= FALSE}

# 2.2

usa2 = st_combine(state_boundaries) %>%
  st_cast("MULTILINESTRING")

cities = cities %>%
  mutate(dist_st_border = st_distance(cities, usa2),
         dist_st_border = set_units(dist_st_border, "km"),
         dist_st_border = drop_units(dist_st_border))

 Top5_state = cities %>%
   select(city, state_name, dist_st_border) %>%
   slice_max(dist_st_border, n = 5) %>%
   st_drop_geometry()

```

```{r, echo = FALSE, message= FALSE}
#Table of top 5 farthest cities from state border 
knitr::kable(Top5_state, caption = 'farthest cities from state border',
             col.names = c("city name", "state", "distance"),
             format.args = list(big.mark = ","))


```

```{r, echo = FALSE, message= FALSE}

# 2.3

mexico = countries %>%
  filter(admin == "Mexico") %>%
  st_union() %>%
  st_cast("MULTILINESTRING")
 
 cities = cities %>%
   mutate(dist_mex = st_distance(cities, mexico),
          dist_mex = set_units(dist_mex, "km"),
          dist_mex = drop_units(dist_mex))

 Top5_mexico = cities %>%
   select(city, state_name, dist_mex) %>%
   slice_max(dist_mex, n = 5) %>%
   st_drop_geometry()

```

```{r, echo = FALSE, message= FALSE}
#Table of top 5 farthest cities from Mexico border
knitr::kable(Top5_mexico, caption = 'farthest cities from Mexico border',
             col.names = c("city name", "state", "distance"),
             format.args = list(big.mark = ","))


```

```{r, echo = FALSE, message= FALSE}

# 2.4

canada = countries %>%
  filter(admin == "Canada") %>%
  st_union() %>%
  st_cast("MULTILINESTRING")
 
 cities = cities %>%
   mutate(dist_can = st_distance(cities, canada),
          dist_can = set_units(dist_can, "km"),
          dist_can = drop_units(dist_can))

 Top5_canada = cities %>%
   select(city, state_name, dist_can) %>%
   slice_max(dist_can, n = 5) %>%
   st_drop_geometry()

```

```{r, echo = FALSE, message= FALSE}
#Table of top 5 farthest cities from Canada border
knitr::kable(Top5_canada, caption = 'farthest cities from Canada border',
             col.names = c("city name", "state", "distance"),
             format.args = list(big.mark = ","))


```

```{r, echo = FALSE, message= FALSE}

# 3.1

big_cities = cities %>%
  slice_max(population, n = 10)

ggplot() +
  geom_sf(data = countries) +
  geom_sf(data = usa2) +
  geom_sf(data = usa, size = .75) +
  geom_sf(data = big_cities, col = "red", size = 1) +
  ggrepel::geom_label_repel(
    data = big_cities,
    aes(label = city, geometry = geometry),
    stat = "sf_coordinates",
    size = 3) +
  labs(title = "10 Largest Cities",
       x = "Longitude",
       y = "Latitude")
  
```

```{r, echo = FALSE, message= FALSE}

# 3.2

city_to_border = cities %>% 
  slice_max(dist_border, n = 5)

ggplot() +
  geom_sf(data = cities, aes(col = dist_border)) +
  geom_sf(data = city_to_border) +
  scale_color_gradient(high = "red", low = "blue") +
  ggrepel::geom_label_repel(
    data = city_to_border,
    aes(label = city, geometry = geometry),
    stat = "sf_coordinates",
    size = 3) +
  labs(title = "City Distance From the US Border")


```

```{r, echo = FALSE, message= FALSE}

# 3.3

city_to_state = cities %>% 
  slice_max(dist_st_border, n = 5)

ggplot() +
  geom_sf(data = cities, aes(color = dist_st_border)) +
  geom_sf(data = city_to_state) +
  scale_color_gradient(high = "red", low = "blue") +
  ggrepel::geom_label_repel(
    data = city_to_state,
    aes(label = city, geometry = geometry),
    stat = "sf_coordinates",
    size = 3) +
  labs(title = "City Distance From Nearest State")

```

```{r, echo = FALSE, message= FALSE}

# 3.4
cities = cities %>% 
  mutate(dist_to_mexcan = abs(dist_can - dist_mex))

Top5_mexcan <- cities %>% 
  filter(dist_to_mexcan < 100) %>% 
  slice_max(population, n = 5)

ggplot() +
  geom_sf(data = cities, aes(color = dist_to_mexcan)) +
  scale_color_gradient(high = "red", low = "blue") +
  gghighlight(dist_to_mexcan < 100) +
  geom_sf(data = Top5_mexcan) +
  ggrepel::geom_label_repel(
    data = Top5_mexcan,
    aes(label = city, geometry = geometry),
    stat = "sf_coordinates",
    size = 3) +
  labs(title = "Equidistance Boudary From Mexico and Canada")

```

```{r, echo = FALSE, message= FALSE}

# 4.1
border_pop = cities %>% 
  filter(dist_border < 160) %>% 
  as_tibble() %>% 
  summarise(count = n(), population = sum(population))
total_pop <- cities %>% 
  as_tibble() %>% 
  summarise(count = n(), population = sum(population))
percent = border_pop$population / total_pop$population * 100
knitr::kable(tibble(border_pop$population, total_pop$population, percent), 
             caption = "Percent of Population Less Than 100 Miles From Border",
             col.names = c("Border Population", "Total Population", "Percent"),
             format.args = list(big.mark = ","))


```

```{r, echo = FALSE, message= FALSE}

# 4.2

border_zone = cities %>% 
  mutate(Mex_cities = dist_mex < 160) %>% 
  mutate(Can_cities = dist_can < 160) %>%
  filter(!Mex_cities %in% "FALSE" | !Can_cities %in% "FALSE")

ggplot() +
  geom_sf(data = (border_pop <- cities %>% 
                    filter(dist_border < 160)), aes(color = dist_border)) +
  scale_color_gradient(high = "red", low = "blue") +
  gghighlight(dist_border < 160) +
  geom_sf(data = (border_pop <- cities %>% 
                    filter(dist_border < 160) %>% 
                    group_by(state_name) %>% 
                    slice_max(population, n = 1))) +
  ggrepel::geom_label_repel(
    data = (border_pop <- cities %>% 
      filter(dist_border < 160) %>% 
      group_by(state_name) %>% 
      slice_max(population, n = 1)),
    aes(label = city, geometry = geometry),
    stat = "sf_coordinates",
    size = 3) +
  labs(title = "100 Mile Border Zone")


```

